# Site settings
title: Guoyi Blog
SEOTitle: 张国毅的博客 | Guoyi Blog
header-img: img/post-bg-desk.jpg
email: zhang_guoyi@qq.com
description: "Every failure is leading towards success."
keyword: "GuoyiZhang, Guoyi Blog, 张国毅的博客,Java, 后端开发,全栈开发, Android"
url: "http://blog.guoyi.pro"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/GuoyiZhang/GuoyiZhang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     GuoyiZhang
#zhihu_username:     GuoyiZhang
github_username:    GuoyiZhang
#facebook_username:  GuoyiZhang
jianshu_username:   GuoyiZhang
#twitter_username:   GuoyiZhang




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
#kramdown:
#  input: GFM                            # use Github Flavored Markdown !important

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: GuoyiZhang

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: guoyizhang.github.io    #仓库名称
  owner: GuoyiZhang    #github用户名
  admin: GuoyiZhang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 6841baa320c4f568e0bc84c575072a75

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: guoyi.pro               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
{
  title: "张国毅",
  href: "http://resume.guoyi.pro"
}
]
